# makefile for the CKconverter directory

ZERORK_ROOT:=$(realpath ../../)
include ../../Makefile.defs

TARG_LIB = libckconverter.a

# list of object files to be created
OBJS = CKParser.o CKReader.o ckr_utils.o Reaction.o thermoFunctions.o \
       writelog.o

LOC_INC_DIR = $(INC_DIR)/CKconverter

include ../Makefile.src.defs
#
