# makefile for the zerork/src/utilities directory

ZERORK_ROOT:=$(realpath ../../)
include ../../Makefile.defs

TARG_LIB = libzerorktransport.a

# list of object files to be created
OBJS = binary_collision.o collision_integrals.o

#TESTS = test_distribution.x

LOC_INC_DIR = $(INC_DIR)/transport

include ../Makefile.src.defs
#
