# makefile for the zerork directory

ZERORK_ROOT:=$(realpath ../../)
include ../../Makefile.defs

TARG_LIB:= libderivative.a
LOC_INC_DIR=$(INC_DIR)/derivative

# list of object files to be created
OBJS:= const_vol.o

include ../Makefile.src.defs
#
