# makefile for the zerork directory

ZERORK_ROOT:=$(realpath ../../)
include ../../Makefile.defs

TARG_LIB:= libmatrix.a
LOC_INC_DIR=$(INC_DIR)/matrix

# list of object files to be created
OBJS:= jacobian_ytv.o jacobian_cmt.o exploded_rop_derivative.o \
       sparsity_pattern.o

include ../Makefile.src.defs
#
