# makefile for the zerork/src/utilities directory

ZERORK_ROOT:=$(realpath ../../)
include ../../Makefile.defs

TARG_LIB = libzerorkutilities.a

# list of object files to be created
OBJS = distribution.o sort_vector.o

TESTS = test_distribution.x

LOC_INC_DIR = $(INC_DIR)/utilities

include ../Makefile.src.defs
#
