
#USER Specifiable Options and External Package Directories

#TODO: Auto-deterimine if zerork has MKL turned on.
#      (May be possible to avoid this if we statically link to 
#       MKL in zerork or use rpath)
USE_MKL:=N
USE_AMD_LIBM:=N
USE_METIS:=N
USE_MPI:=N
USE_ARKODE:=N

DEFS:=

ZERORKROOT:=../zerork
SUPERLUROOT:=../opt/SuperLU_4.3
SUNDIALSROOT:=../opt/sundials-2.5.0
METISROOT:=/dummy/path   #only necessary if USE_METIS=Y
MKLROOT:=/dummy/path     #only necessary if USE_MKL=Y
AMDLIBMROOT:=/dummy/path #only necessay if USE_AMDLIBM=Y
SPIFYROOT:=../opt

CC:=gcc
CXX:=g++

ifeq ($(USE_MPI),Y)
  CC:=mpicc
  CXX:=mpicxx
  DEFS+= -DUSE_MPI
endif

OPT_FLAGS:= -O3

# C++ compile flags
CXX_FLAGS:= $(OPT_FLAGS) -fPIC -fopenmp -std=c++11

#DEFS+= -DCONVERGE_DPDT_UNITS
#DEFS+= -DCONVERGE_CONST_PRESS
#DEFS+= -DZERORK_USE_SAGE_RHS
#DEFS+= -DZERORK_CONVERGE_RELEASE
#DEFS+= -DZERORK_TRAP_FE
#DEFS+= -DZERORK_GPU_ONLY
#DEFS+= -DZERORK_NEG_CONC_CHECK
#DEFS+= -DZERORK_DUMP_REACTORS

