
option(ENABLE_CEQ "Enable interface to CEQ. User must obtain CEQ from original authors." OFF)
set(ZERORK_HAVE_CEQ OFF)

if(ENABLE_CEQ)
  if(NOT EXISTS ${CMAKE_BINARY_DIR}/external/CEQ/)
    set(CEQ_TARFILE ${CMAKE_BINARY_DIR}/external/ceq.tar)
    #set(CEQ_TAR_OK off)
    if(EXISTS ${CEQ_TARFILE})
      file(MD5 ${CEQ_TARFILE} CEQ_TARFILE_HASH)
      if(${CEQ_TARFILE_HASH} STREQUAL "b08c6c8e006c1546a7114e6b2b670f04")
        set(ZERORK_HAVE_CEQ ON)
        enable_language(Fortran)
        message(STATUS "Extracting CEQ tarball...")
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xf ${CEQ_TARFILE}
                        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/external
                        RESULT_VARIABLE result)
        if(result)
          message(FATAL_ERROR "Failed to extract CEQ tarball: ${result}")
        endif()
      else()
        message(STATUS "${CEQ_TARFILE} doesn't match expected file. Disabling CEQ interface.")
      endif()
    else()
      message(STATUS "Can't find ${CEQ_TARFILE}. Please obtain from original authors.")
    endif()
  else()
    set(ZERORK_HAVE_CEQ ON)
    enable_language(Fortran)
  endif()
endif()
